# Mesh

In [9]:
import open3d as o3d
import matplotlib.pyplot as plt
import numpy as np
import cv2
import copy

## Reading Mesh Files

In [2]:
armadillo_mesh = o3d.data.ArmadilloMesh()
armadillomesh = o3d.io.read_triangle_mesh(armadillo_mesh.path)

knot_mesh = o3d.data.KnotMesh()
knotmesh = o3d.io.read_triangle_mesh(knot_mesh.path)
print(armadillomesh)
print(knotmesh)
print("Vertices:")
print(np.asarray(armadillomesh.vertices))
print("Triangles:")
print(np.asarray(armadillomesh.triangles))

[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/ArmadilloMesh.ply
[Open3D INFO] Downloaded to C:\Users\nazib/open3d_data/download/ArmadilloMesh/ArmadilloMesh.ply
[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/KnotMesh.ply
[Open3D INFO] Downloaded to C:\Users\nazib/open3d_data/download/KnotMesh/KnotMesh.ply
TriangleMesh with 172974 points and 345944 triangles.
TriangleMesh with 1440 points and 2880 triangles.
Vertices:
[[  5.8945775   11.78840065  27.28323936]
 [-53.32511139  67.10436249 -57.45013046]
 [  3.75048876  16.50540161  29.45401955]
 ...
 [ -0.53707075  -6.22242689  42.90413666]
 [-49.76054001 -52.08040619   1.24506998]
 [-57.97610855  62.83114624 -50.2011261 ]]
Triangles:
[[170671  67345  67377]
 [ 16306   9985   5355]
 [ 73048  97544  97343]
 ...
 [  2016   2011   1853]
 [  1854   2009   1692]
 [  1685   2009   2003]]


### Visualize

In [4]:
# o3d.visualization.draw_geometries([knotmesh])

## Surface Normal Estimation

In [8]:
knotmesh.compute_vertex_normals()
knotmesh.paint_uniform_color([0.1, 0.1, 0.7]) # For coloring the mesh
o3d.visualization.draw_geometries([knotmesh])

## Cropping Mesh

In [10]:
mesh1 = copy.deepcopy(knotmesh)
mesh1.triangles = o3d.utility.Vector3iVector(np.asarray(mesh1.triangles)[:len(mesh1.triangles)//2, :]) # 3 element integer vector
mesh1.triangle_normals = o3d.utility.Vector3dVector(np.asarray(mesh1.triangle_normals)[:len(mesh1.triangle_normals)//2, :]) # 3 element double vector

o3d.visualization.draw_geometries([mesh1])