In [2]:
import open3d as o3d
import numpy as np
import os
import sys

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [6]:
pcd = o3d.io.read_point_cloud("armadillo.ply")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

PointCloud with 172974 points.
[[-10.6115799   -1.50496352 -18.488657  ]
 [-10.45836926  -1.50496352 -18.03206253]
 [-10.6115799   -1.80833614 -18.03206253]
 ...
 [-41.91530228  52.09729385  -6.18760586]
 [ 14.69301319  -0.64079708 -20.6011467 ]
 [ 47.21072769 -48.32879257  -5.75543213]]
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 


In [10]:
pcd = o3d.io.read_point_cloud("fragment.ply")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

PointCloud with 196133 points.
[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]


In [12]:
o3d.visualization.draw_geometries([o3d.data.BunnyMesh()])

[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/BunnyMesh.ply
[Open3D INFO] Downloaded to C:\Users\nazib/open3d_data/download/BunnyMesh/BunnyMesh.ply


TypeError: draw_geometries(): incompatible function arguments. The following argument types are supported:
    1. (geometry_list: list[open3d.cpu.pybind.geometry.Geometry], window_name: str = 'Open3D', width: int = 1920, height: int = 1080, left: int = 50, top: int = 50, point_show_normal: bool = False, mesh_show_wireframe: bool = False, mesh_show_back_face: bool = False, lookat: Optional[numpy.ndarray[numpy.float64[3, 1]]] = None, up: Optional[numpy.ndarray[numpy.float64[3, 1]]] = None, front: Optional[numpy.ndarray[numpy.float64[3, 1]]] = None, zoom: Optional[float] = None) -> None

Invoked with: [<open3d.cpu.pybind.data.BunnyMesh object at 0x000001B7CFEFCEF0>]